# Generated by Django 5.1.6 on 2026-09-10 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "i18n",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Tarjimalar"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                ("name", models.CharField(max_length=60, verbose_name="Tarif nomi")),
                (
                    "code",
                    models.SlugField(max_length=40, unique=True, verbose_name="Kod"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Qisqa tavsif"
                    ),
                ),
                (
                    "features_text",
                    models.TextField(
                        blank=True,
                        help_text="Har bir imkoniyat alohida qatorda yozilsin",
                        verbose_name="Imkoniyatlar",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Narxi (so'm)",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Eski narxi",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("month", "Oylik"), ("year", "Yillik")],
                        default="month",
                        max_length=8,
                        verbose_name="Muddat turi",
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Amal qilish muddati (kun)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "is_popular",
                    models.BooleanField(
                        default=False, verbose_name="Eng ommabop (ajratib ko'rsatilsin)"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#1F6FEB", max_length=9, verbose_name="Rang"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Tartib"),
                ),
            ],
            options={
                "verbose_name": "Premium tarif",
                "verbose_name_plural": "Premium tariflar",
                "ordering": ("order", "price"),
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "plan_name",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Tarif nomi"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Summa"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "To'lov kutilmoqda"),
                            ("active", "Faol"),
                            ("expired", "Muddati tugagan"),
                            ("cancelled", "Bekor qilingan"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Boshlanish"
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Tugash"),
                ),
                (
                    "is_auto_renew",
                    models.BooleanField(
                        default=False, verbose_name="Avtomatik yangilash"
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Qo'lda bergan admin",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="billing.plan",
                        verbose_name="Tarif",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Obuna",
                "verbose_name_plural": "Obunalar",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=32,
                        unique=True,
                        verbose_name="Ichki raqam",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("payme", "Payme"),
                            ("click", "Click"),
                            ("manual", "Qo'lda"),
                        ],
                        default="payme",
                        max_length=10,
                        verbose_name="To'lov tizimi",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("subscription", "Premium obuna"),
                            ("order", "Do'kon buyurtmasi"),
                            ("course", "Kurs"),
                        ],
                        default="subscription",
                        max_length=16,
                        verbose_name="Nima uchun",
                    ),
                ),
                (
                    "target_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Obyekt ID"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Summa (so'm)",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("created", "Yaratilgan"),
                            ("hold", "Ushlab turilgan"),
                            ("paid", "To'langan"),
                            ("cancelled", "Bekor qilingan"),
                        ],
                        default="created",
                        max_length=12,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Tashqi tranzaksiya ID",
                    ),
                ),
                (
                    "perform_time",
                    models.BigIntegerField(
                        default=0, verbose_name="To'langan vaqt (ms)"
                    ),
                ),
                (
                    "cancel_time",
                    models.BigIntegerField(
                        default=0, verbose_name="Bekor qilingan vaqt (ms)"
                    ),
                ),
                (
                    "create_time",
                    models.BigIntegerField(
                        default=0, verbose_name="Yaratilgan vaqt (ms)"
                    ),
                ),
                (
                    "cancel_reason",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Bekor qilish sababi"
                    ),
                ),
                (
                    "raw",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Xom javob"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "To'lov",
                "verbose_name_plural": "To'lovlar",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["provider", "external_id"],
                        name="billing_pay_provide_3bfd59_idx",
                    )
                ],
            },
        ),
    ]
