# Generated by Django 5.1.6 on 2026-09-12 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('code', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Kod')),
                ('discount_percent', models.PositiveSmallIntegerField(default=10, verbose_name='Chegirma (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('max_uses', models.PositiveIntegerField(default=0, verbose_name='Maksimal ishlatilish soni (0 — cheklanmagan)')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Ishlatilgan soni')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Promo kod',
                'verbose_name_plural': 'Promo kodlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.promocode', verbose_name='Promo kod'),
        ),
    ]
