# Generated by Django 5.1.6 on 2026-09-10 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "i18n",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Tarjimalar"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                ("title", models.CharField(max_length=140, verbose_name="Sarlavha")),
                ("subtitle", models.TextField(blank=True, verbose_name="Matn")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="banners/", verbose_name="Banner rasmi"
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Tugma matni"
                    ),
                ),
                (
                    "button_url",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Tugma havolasi"
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("home", "Bosh sahifa"),
                            ("courses", "Kurslar sahifasi"),
                            ("shop", "Do'kon sahifasi"),
                        ],
                        default="home",
                        max_length=16,
                        verbose_name="Joylashuv",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Boshlanish sanasi"
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tugash sanasi"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Tartib"),
                ),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Bannerlar",
                "ordering": ("order", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="DailyStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Sana")),
                (
                    "new_users",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Yangi foydalanuvchilar"
                    ),
                ),
                (
                    "active_users",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Faol foydalanuvchilar"
                    ),
                ),
                (
                    "enrollments",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Kursga yozilishlar"
                    ),
                ),
                (
                    "orders",
                    models.PositiveIntegerField(default=0, verbose_name="Buyurtmalar"),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Daromad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kunlik statistika",
                "verbose_name_plural": "Kunlik statistika",
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="VECTOR", max_length=80, verbose_name="Sayt nomi"
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="O'zbekistondagi 1-raqamli onlayn ta'lim platformasi",
                        max_length=160,
                        verbose_name="Shior",
                    ),
                ),
                (
                    "support_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Qo'llab-quvvatlash raqami",
                    ),
                ),
                (
                    "support_telegram",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Telegram"
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Instagram"
                    ),
                ),
                (
                    "youtube",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="YouTube"
                    ),
                ),
                (
                    "android_url",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Google Play havolasi"
                    ),
                ),
                (
                    "ios_url",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="App Store havolasi"
                    ),
                ),
                (
                    "terms_url",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Foydalanish shartnomasi havolasi",
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False, verbose_name="Texnik ish rejimi"
                    ),
                ),
                (
                    "default_language",
                    models.CharField(
                        default="uz", max_length=10, verbose_name="Standart til"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sayt sozlamasi",
                "verbose_name_plural": "Sayt sozlamalari",
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Qo'shildi"),
                            ("update", "O'zgartirildi"),
                            ("delete", "O'chirildi"),
                        ],
                        max_length=10,
                    ),
                ),
                ("model_name", models.CharField(max_length=60)),
                ("object_id", models.CharField(blank=True, max_length=40)),
                ("description", models.CharField(blank=True, max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Amal jurnali",
                "verbose_name_plural": "Amallar jurnali",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "i18n",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Tarjimalar"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                ("title", models.CharField(max_length=140, verbose_name="Sarlavha")),
                ("body", models.TextField(verbose_name="Matn")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="notifications/", verbose_name="Rasm"
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all", "Barcha foydalanuvchilar"),
                            ("premium", "Faqat premium"),
                            ("free", "Faqat oddiy"),
                            ("students", "O'quvchilar"),
                            ("teachers", "O'qituvchilar"),
                            ("course", "Muayyan kurs o'quvchilari"),
                        ],
                        default="all",
                        max_length=16,
                        verbose_name="Kimga",
                    ),
                ),
                (
                    "send_push",
                    models.BooleanField(default=True, verbose_name="Push yuborilsin"),
                ),
                (
                    "send_telegram",
                    models.BooleanField(
                        default=False, verbose_name="Telegramga ham yuborilsin"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Qoralama"), ("sent", "Yuborilgan")],
                        default="draft",
                        max_length=10,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Yuborilgan vaqt"
                    ),
                ),
                (
                    "recipients_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Qabul qiluvchilar"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kim yaratdi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildirishnoma",
                "verbose_name_plural": "Bildirishnomalar",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="O'qilgan"),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="core.notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Yetkazilgan bildirishnoma",
                "verbose_name_plural": "Yetkazilgan bildirishnomalar",
                "ordering": ("-created_at",),
                "unique_together": {("notification", "user")},
            },
        ),
    ]
