# Generated by Django 5.1.6 on 2026-09-10 19:26

import accounts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True,
                        max_length=13,
                        unique=True,
                        verbose_name="Telefon raqam",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=120, verbose_name="Ism va familiya"),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=80, verbose_name="Viloyat"),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Shahar yoki tuman"
                    ),
                ),
                (
                    "school",
                    models.CharField(blank=True, max_length=80, verbose_name="Maktab"),
                ),
                (
                    "grade",
                    models.CharField(blank=True, max_length=20, verbose_name="Sinf"),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tug'ilgan sana"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "O'quvchi"),
                            ("teacher", "O'qituvchi"),
                            ("admin", "Administrator"),
                        ],
                        db_index=True,
                        default="student",
                        max_length=16,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        verbose_name="Fan (o'qituvchilar uchun)",
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        blank=True, null=True, unique=True, verbose_name="Telegram ID"
                    ),
                ),
                (
                    "telegram_username",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Telegram username"
                    ),
                ),
                (
                    "is_phone_verified",
                    models.BooleanField(
                        default=False, verbose_name="Raqam tasdiqlangan"
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="Faol")),
                ("is_staff", models.BooleanField(default=False, verbose_name="Xodim")),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Ro'yxatdan o'tgan sana",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foydalanuvchi",
                "verbose_name_plural": "Foydalanuvchilar",
                "ordering": ("-date_joined",),
            },
            managers=[
                ("objects", accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="TelegramVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=13, verbose_name="Telefon raqam"
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("register", "Ro'yxatdan o'tish"),
                            ("login", "Kirish"),
                            ("reset", "Parolni tiklash"),
                        ],
                        default="register",
                        max_length=16,
                        verbose_name="Maqsad",
                    ),
                ),
                (
                    "start_token",
                    models.CharField(
                        db_index=True,
                        max_length=48,
                        unique=True,
                        verbose_name="Start token",
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Kod (hash)"
                    ),
                ),
                (
                    "telegram_chat_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Telegram chat ID"
                    ),
                ),
                (
                    "code_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Kod yuborilgan vaqt"
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Urinishlar"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="Ishlatilgan"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(verbose_name="Amal qilish muddati"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram tasdiqlash",
                "verbose_name_plural": "Telegram tasdiqlashlar",
                "ordering": ("-created_at",),
            },
        ),
    ]
