# Generated by Django 5.1.6 on 2026-09-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.PositiveIntegerField(default=0, verbose_name='Coin balansi'),
        ),
        migrations.AddField(
            model_name='user',
            name='promo_code_used',
            field=models.CharField(blank=True, max_length=40, verbose_name='Ishlatilgan promo kod'),
        ),
        migrations.AddField(
            model_name='user',
            name='promo_discount_applied',
            field=models.BooleanField(default=False, verbose_name='Promo chegirma ishlatilgan'),
        ),
    ]
