# Generated by Django 5.1.6 on 2026-09-10 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "i18n",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Tarjimalar"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                ("name", models.CharField(max_length=90, verbose_name="Nomi")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=110, unique=True, verbose_name="Slug"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Tavsif")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        verbose_name="Ikonka (emoji yoki nom)",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#1F6FEB", max_length=9, verbose_name="Rang"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="categories/", verbose_name="Rasm"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Tartib"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
            ],
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar",
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "i18n",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Tarjimalar"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                ("title", models.CharField(max_length=160, verbose_name="Dars nomi")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Qisqa tavsif"
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="Dars matni")),
                (
                    "video_source",
                    models.CharField(
                        choices=[
                            ("telegram", "Telegram (yopiq kanal)"),
                            ("url", "Tashqi havola"),
                            ("none", "Videosiz"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="Video manbasi",
                    ),
                ),
                (
                    "video_url",
                    models.CharField(
                        blank=True,
                        help_text="YouTube, Vimeo yoki to'g'ridan-to'g'ri MP4",
                        max_length=400,
                        verbose_name="Video havolasi",
                    ),
                ),
                (
                    "telegram_file_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Telegram file_id"
                    ),
                ),
                (
                    "telegram_message_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Telegram xabar ID"
                    ),
                ),
                (
                    "video_size",
                    models.BigIntegerField(
                        default=0, verbose_name="Video hajmi (bayt)"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, upload_to="lessons/", verbose_name="Video muqovasi"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Davomiyligi (soniya)"
                    ),
                ),
                (
                    "is_free",
                    models.BooleanField(
                        default=False, verbose_name="Bepul (demo dars)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Tartib"),
                ),
            ],
            options={
                "verbose_name": "Dars",
                "verbose_name_plural": "Darslar",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "i18n",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Tarjimalar"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                ("title", models.CharField(max_length=160, verbose_name="Kurs nomi")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=180, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Qisqa tavsif"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="To'liq tavsif"),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True, upload_to="courses/", verbose_name="Kurs rasmi"
                    ),
                ),
                (
                    "teacher_name",
                    models.CharField(
                        blank=True,
                        help_text="Agar o'qituvchi tizimda ro'yxatdan o'tmagan bo'lsa",
                        max_length=120,
                        verbose_name="O'qituvchi ismi (matn)",
                    ),
                ),
                (
                    "access",
                    models.CharField(
                        choices=[
                            ("free", "Bepul"),
                            ("premium", "Premium obuna bilan"),
                            ("paid", "Alohida sotib olinadi"),
                        ],
                        default="premium",
                        max_length=10,
                        verbose_name="Kirish turi",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Narxi (so'm)",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Eski narxi",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Boshlang'ich"),
                            ("middle", "O'rta"),
                            ("advanced", "Yuqori"),
                        ],
                        default="beginner",
                        max_length=12,
                        verbose_name="Daraja",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Bosh sahifada ko'rsatilsin"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Tartib"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="E'lon qilingan"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to="courses.category",
                        verbose_name="Kategoriya",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role__in": ["teacher", "admin"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teaching_courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'qituvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kurs",
                "verbose_name_plural": "Kurslar",
                "ordering": ("order", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="LessonAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="Fayl nomi")),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to="attachments/", verbose_name="Fayl"
                    ),
                ),
                (
                    "telegram_file_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Telegram file_id"
                    ),
                ),
                (
                    "size",
                    models.BigIntegerField(default=0, verbose_name="Hajmi (bayt)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dars fayli",
                "verbose_name_plural": "Dars fayllari",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "i18n",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Tarjimalar"
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="Modul nomi")),
                ("description", models.TextField(blank=True, verbose_name="Tavsif")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Tartib"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="courses.course",
                        verbose_name="Kurs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modul",
                "verbose_name_plural": "Modullar",
                "ordering": ("order", "id"),
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="courses.module",
                verbose_name="Modul",
            ),
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Sertifikat raqami"
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sertifikat",
                "verbose_name_plural": "Sertifikatlar",
                "ordering": ("-issued_at",),
                "unique_together": {("user", "course")},
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Progress (%)"
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="To'langan"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Tugatilgan"),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_opened_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Oxirgi ochilgan"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="courses.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kursga yozilish",
                "verbose_name_plural": "Kursga yozilishlar",
                "ordering": ("-created_at",),
                "unique_together": {("user", "course")},
            },
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Tugatilgan"),
                ),
                (
                    "seconds_watched",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ko'rilgan vaqt (soniya)"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="courses.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dars progressi",
                "verbose_name_plural": "Dars progresslari",
                "unique_together": {("user", "lesson")},
            },
        ),
    ]
