# Generated by Django 5.1.6 on 2026-09-12 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_reward', models.PositiveIntegerField(default=10, help_text="Test 100% to'g'ri yechilsa shuncha Coin beriladi; qisman yechilsa ulushi bo'yicha.", verbose_name='Maksimal Coin mukofoti')),
                ('pass_percent', models.PositiveSmallIntegerField(default=60, verbose_name="O'tish balli (%)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Dars testi',
                'verbose_name_plural': 'Dars testlari',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Savol matni')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.lessonquiz')),
            ],
            options={
                'verbose_name': 'Test savoli',
                'verbose_name_plural': 'Test savollari',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Javob varianti')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='courses.quizquestion')),
            ],
            options={
                'verbose_name': 'Javob varianti',
                'verbose_name_plural': 'Javob variantlari',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Natija (%)')),
                ('correct_count', models.PositiveSmallIntegerField(default=0, verbose_name="To'g'ri javoblar soni")),
                ('total_count', models.PositiveSmallIntegerField(default=0, verbose_name='Jami savollar')),
                ('coins_earned', models.PositiveIntegerField(default=0, verbose_name='Berilgan Coin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.lessonquiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test urinishi',
                'verbose_name_plural': 'Test urinishlari',
                'ordering': ('-created_at',),
                'unique_together': {('user', 'quiz')},
            },
        ),
    ]
