# Generated by Django 5.1.6 on 2026-09-10 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "i18n",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Tarjimalar"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "name",
                    models.CharField(max_length=140, verbose_name="Mahsulot nomi"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=160, unique=True, verbose_name="Slug"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Tavsif")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="products/", verbose_name="Rasmi"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Narxi (so'm)",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Eski narxi",
                    ),
                ),
                ("stock", models.IntegerField(default=0, verbose_name="Qoldiq soni")),
                (
                    "sku",
                    models.CharField(blank=True, max_length=40, verbose_name="Artikul"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Sotuvda"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Tavsiya etilgan"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Tartib"),
                ),
            ],
            options={
                "verbose_name": "Mahsulot",
                "verbose_name_plural": "Mahsulotlar",
                "ordering": ("order", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "i18n",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Tarjimalar"
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Nomi")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Tartib"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
            ],
            options={
                "verbose_name": "Mahsulot kategoriyasi",
                "verbose_name_plural": "Mahsulot kategoriyalari",
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Buyurtma raqami",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=120, verbose_name="Qabul qiluvchi"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Telefon")),
                ("address", models.TextField(blank=True, verbose_name="Manzil")),
                ("comment", models.TextField(blank=True, verbose_name="Izoh")),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Umumiy summa",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Yangi"),
                            ("paid", "To'langan"),
                            ("shipped", "Yuborilgan"),
                            ("done", "Yakunlangan"),
                            ("cancelled", "Bekor qilingan"),
                        ],
                        default="new",
                        max_length=12,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="To'langan vaqt"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyurtma",
                "verbose_name_plural": "Buyurtmalar",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=140, verbose_name="Mahsulot nomi"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Narxi"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Soni"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shop.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyurtma qatori",
                "verbose_name_plural": "Buyurtma qatorlari",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="shop.productcategory",
                verbose_name="Kategoriya",
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="products/", verbose_name="Rasm"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Tartib"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mahsulot rasmi",
                "verbose_name_plural": "Mahsulot rasmlari",
                "ordering": ("order", "id"),
            },
        ),
    ]
