# Generated by Django 5.1.6 on 2026-09-12 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coin_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Umumiy Coin'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_via_coin',
            field=models.BooleanField(default=False, verbose_name="Coin orqali to'langan"),
        ),
        migrations.AddField(
            model_name='product',
            name='coin_price',
            field=models.PositiveIntegerField(default=0, help_text="0 bo'lsa — mahsulot Coin do'konida (Sovg'a bo'limida) ko'rinmaydi.", verbose_name='Narxi (Coin)'),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Baho (1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mahsulot sharhi',
                'verbose_name_plural': 'Mahsulot sharhlari',
                'ordering': ('-created_at',),
                'unique_together': {('product', 'user')},
            },
        ),
    ]
